# Generated by Django 3.2.9 on 2021-11-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(blank=True, max_length=5000, null=True, verbose_name='Endpoint URL')),
                ('key_auth', models.CharField(blank=True, max_length=500, null=True, verbose_name='Auth key')),
                ('key_p256dh', models.CharField(blank=True, max_length=500, null=True, verbose_name='p256dh key')),
            ],
            options={
                'verbose_name': 'Подписка пользователя на Push',
                'verbose_name_plural': 'Подписки поьзователей на Push',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='webpush',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_api.webpushsubscription', verbose_name='WebPush Tokens'),
        ),
    ]
