# Generated by Django 3.2.9 on 2021-11-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_auto_20211127_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpushsubscription',
            old_name='key_p256dh',
            new_name='key_secret',
        ),
    ]
