# Generated by Django 3.2.9 on 2021-11-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendnotice',
            name='date_of_execution',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исполнения'),
        ),
        migrations.AddField(
            model_name='sendnotice',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
