# Generated by Django 3.2.9 on 2021-11-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20211127_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Низкий приоритет'), (2, 'Средний приоритет'), (3, 'Высокий приоритет')], verbose_name='Приоритет'),
        ),
    ]
