# Generated by Django 3.2.9 on 2021-11-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_event_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Группа событий',
                'verbose_name_plural': 'Группы событий',
            },
        ),
        migrations.RemoveField(
            model_name='sendnotice',
            name='state',
        ),
        migrations.AddField(
            model_name='sendnotice',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Являеется архивным'),
        ),
        migrations.AddField(
            model_name='sendnotice',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Являеется просмотренным'),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='notice.groupevent'),
        ),
    ]
