# Generated by Django 3.2.9 on 2021-11-27 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20211127_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendnotice',
            name='date_of_execution',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата исполнения'),
        ),
        migrations.AlterField(
            model_name='sendnotice',
            name='date_of_send',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='sendnotice',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.notice', verbose_name='Отправленное уведомление'),
        ),
    ]
