# Generated by Django 3.2.9 on 2021-11-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_alter_event_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='notice.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='sendnotice',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_notices', to='notice.notice', verbose_name='Отправленное уведомление'),
        ),
    ]
